# Generated by Django 6.1 on 2026-09-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_journalactivite'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='adjoint',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='departement',
            name='date_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='departement',
            name='responsable',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='departement',
            name='telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
