# Generated by Django 6.1 on 2026-09-08 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_eglise_alter_departement_nom_departement_eglise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoboConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.TextField()),
                ('base_url', models.URLField(default='https://kf.kobotoolbox.org')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('eglise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kobo_configuration', to='core.eglise')),
            ],
        ),
    ]
