# Generated by Django 6.1 on 2026-09-08 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_koboconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoboFormulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('achats', 'Achats'), ('finances', 'Finances'), ('depenses', 'Dépenses'), ('membres', 'Membres'), ('nouveaux_membres', 'Nouveaux membres'), ('inventaire', 'Inventaire'), ('suivi_activites', 'Suivi des activités'), ('evaluations_suivi', 'Évaluations du suivi'), ('renseignements_culte', 'Renseignements du culte'), ('preuves_paiement', 'Preuves de paiement')], max_length=50)),
                ('uid', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('eglise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kobo_formulaires', to='core.eglise')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('eglise', 'nom'), name='unique_kobo_formulaire_eglise_nom'), models.UniqueConstraint(fields=('eglise', 'uid'), name='unique_kobo_formulaire_eglise_uid')],
            },
        ),
    ]
