# Generated by Django 6.1 on 2026-09-07 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_eglise_alter_departement_nom_departement_eglise_and_more'),
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='eglise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.eglise'),
        ),
        migrations.AddField(
            model_name='nouveaumembre',
            name='eglise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.eglise'),
        ),
    ]
