# Generated by Django 6.1 on 2026-08-28 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgence', models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('urgente', 'Urgente')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('kobo_uuid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.departement')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.statut')),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_depense', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Especes'), ('mobile money', 'Mobile money'), ('banque', 'Banque')], max_length=30)),
                ('date_transaction', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('kobo_uuid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.departement')),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.devise')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.statut')),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('offrande', 'Offrande'), ('dime', 'Dime'), ('don', 'Don'), ('action de grace', 'Action de grace')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('membre_type', models.CharField(choices=[('existant', 'Membre existant'), ('nouveau membre', 'Nouveau membre'), ('inconnu', 'Inconnu'), ('eglise', 'Eglise')], max_length=20)),
                ('date_transaction', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('kobo_uuid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.devise')),
                ('membre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membres.membre')),
            ],
        ),
        migrations.CreateModel(
            name='PreuvePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Especes'), ('mobile money', 'Mobile money'), ('banque', 'Banque')], max_length=30)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='preuves_paiement/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('kobo_uuid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.departement')),
                ('depense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.depense')),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.devise')),
            ],
        ),
    ]
