# Generated by Django 6.1 on 2026-09-03 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_journalactivite'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('montant_prevu', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.departement')),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.devise')),
            ],
            options={
                'unique_together': {('departement', 'annee')},
            },
        ),
    ]
