# Generated by Django 6.1 on 2026-09-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_departement_adjoint_departement_date_creation_and_more'),
        ('finance', '0002_budget'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('departement', 'annee', 'devise')},
        ),
    ]
