# Generated by Django 6.1 on 2026-09-07 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_eglise_alter_departement_nom_departement_eglise_and_more'),
        ('finance', '0003_alter_budget_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='eglise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.eglise'),
        ),
        migrations.AddField(
            model_name='budget',
            name='eglise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.eglise'),
        ),
        migrations.AddField(
            model_name='depense',
            name='eglise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.eglise'),
        ),
        migrations.AddField(
            model_name='finance',
            name='eglise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.eglise'),
        ),
        migrations.AddField(
            model_name='preuvepaiement',
            name='eglise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.eglise'),
        ),
    ]
