# Generated by Django 6.1 on 2026-08-29 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('membres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementCalendrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('culte', 'Culte'), ('reunion', 'Reunion'), ('formation', 'Formation'), ('conference', 'Conference'), ('mariage', 'Mariage'), ('autre', 'Autre')], max_length=15)),
                ('date_debut', models.DateField()),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.departement')),
            ],
        ),
        migrations.CreateModel(
            name='RendezVousPasteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_visiteur', models.CharField(blank=True, max_length=150)),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('motif', models.CharField(blank=True, max_length=200)),
                ('lieu', models.CharField(blank=True, max_length=150)),
                ('statut', models.CharField(choices=[('prevu', 'Prevu'), ('confirme', 'Confirme'), ('termine', 'Termine'), ('annule', 'Annule')], default='prevu', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('membre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membres.membre')),
                ('pasteur', models.ForeignKey(limit_choices_to={'role': 'pasteur'}, on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
