# Generated by Django 6.1 on 2026-09-07 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('core', '0004_eglise_alter_departement_nom_departement_eglise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenementcalendrier',
            name='eglise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evenements_calendrier', to='core.eglise'),
        ),
        migrations.AddField(
            model_name='rendezvouspasteur',
            name='eglise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous_pasteurs', to='core.eglise'),
        ),
    ]
