# Generated by Django 6.1 on 2026-09-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('administrateur', 'Administrateur'), ('chef_departement', 'Chef de departement'), ('pasteur', 'Pasteur'), ('secretaire', 'Secretaire'), ('tresorier', 'Tresorier')], max_length=20),
        ),
    ]
