# Generated by Django 6.1 on 2026-09-06 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_alter_utilisateur_role'),
        ('core', '0004_eglise_alter_departement_nom_departement_eglise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='eglise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.eglise'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super administrateur'), ('administrateur', 'Administrateur'), ('chef_departement', 'Chef de departement'), ('pasteur', 'Pasteur'), ('secretaire', 'Secretaire'), ('tresorier', 'Tresorier')], max_length=20),
        ),
    ]
