# Generated by Django 6.1 on 2026-09-07 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_utilisateur_eglise_alter_utilisateur_role'),
        ('core', '0004_eglise_alter_departement_nom_departement_eglise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='departement',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='eglise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.eglise'),
        ),
    ]
