# Generated by Django 6.1 on 2026-08-28 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_article', models.CharField(blank=True, max_length=150)),
                ('type', models.CharField(choices=[('mobilier', 'Mobilier'), ('equipement', 'Equipement'), ('instrument', 'Instrument'), ('autre', 'Autre')], max_length=20)),
                ('localisation', models.CharField(choices=[('salle principale', 'Salle principale'), ('bureau', 'Bureau'), ('reserve', 'Reserve'), ('exterieur', 'Exterieur')], max_length=20)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('kobo_uuid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RenseignementCulte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_predicateur', models.CharField(choices=[('interne', 'Interne'), ('invite', 'Invite'), ('autre', 'Autre')], max_length=10)),
                ('type_culte', models.CharField(choices=[('dimanche', 'Dimanche'), ('semaine', 'Semaine'), ('special', 'Special'), ('veille', 'Veille')], max_length=10)),
                ('nom_predicateur', models.CharField(blank=True, max_length=100)),
                ('date_culte', models.DateField()),
                ('kobo_uuid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationSuivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction', models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('elevee', 'Elevee')], max_length=10)),
                ('probleme', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True)),
                ('kobo_uuid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.departement')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.statut')),
            ],
        ),
        migrations.CreateModel(
            name='SuiviActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('date_activite', models.DateField(blank=True, null=True)),
                ('kobo_uuid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.departement')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.statut')),
            ],
        ),
    ]
