# Generated by Django 6.1 on 2026-09-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_culte', models.DateField()),
                ('type_culte', models.CharField(choices=[('dimanche', 'Culte dimanche'), ('semaine', 'Culte semaine'), ('special', 'Culte special'), ('veille', 'Veillee'), ('activite', 'Autre activite')], default='dimanche', max_length=15)),
                ('nom_activite', models.CharField(blank=True, max_length=150)),
                ('hommes', models.PositiveIntegerField(default=0)),
                ('femmes', models.PositiveIntegerField(default=0)),
                ('enfants', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('kobo_uuid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
            options={
                'ordering': ['-date_culte'],
            },
        ),
    ]
