# Generated by Django 6.1 on 2026-09-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_presence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_predication', models.DateField()),
                ('predicateur', models.CharField(max_length=150)),
                ('theme', models.CharField(max_length=200)),
                ('texte_biblique', models.CharField(blank=True, max_length=150)),
                ('type_culte', models.CharField(choices=[('dimanche', 'Culte dimanche'), ('semaine', 'Culte semaine'), ('special', 'Culte special'), ('conference', 'Conference')], default='dimanche', max_length=15)),
                ('duree_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('resume', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_predication'],
            },
        ),
    ]
