# Generated by Django 6.1 on 2026-09-07 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_eglise_alter_departement_nom_departement_eglise_and_more'),
        ('operations', '0003_predication'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationsuivi',
            name='eglise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.eglise'),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='eglise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.eglise'),
        ),
        migrations.AddField(
            model_name='predication',
            name='eglise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.eglise'),
        ),
        migrations.AddField(
            model_name='presence',
            name='eglise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.eglise'),
        ),
        migrations.AddField(
            model_name='renseignementculte',
            name='eglise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.eglise'),
        ),
        migrations.AddField(
            model_name='suiviactivite',
            name='eglise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.eglise'),
        ),
    ]
